### PR TITLE
fixes #34; removed tabs in code; fixes deprecation warning

### LINKED ISSUE #34: Syslog logger ignores message priority
Not quite true, it seems to use the message priority internally for filtering, but seems to use the _handler's_ priority in the message that goes to syslog rather than the message's priority.

A couple of lines from a `strace` output:

    5797  sendto(22, "<134>cluster[5797]: [cluster/INF"..., 56, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 56
    5800  sendto(22, "<134>cluster[5797]: [cluster/WAR"..., 105, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 1

`<134>` is `local0.info` which is correct for the first line but wrong for the second as that was sent with WARNING priority.

My handler is created with

    sysLog <- openlog "cluster" [PID] LOCAL0 INFO

If I change this to

    sysLog <- openlog "cluster" [PID] LOCAL0 DEBUG

(but change nothing else) then the messages are logged at DEBUG priority (`<135>`):

    6055  sendto(22, "<135>cluster[6055]: [cluster/INF"..., 56, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 56
    6056  sendto(22, "<135>cluster[6055]: [cluster/WAR"..., 105, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 1

First noticed in 1.2.8 but still seems to be an issue in HEAD (c9433f88beac13a51f2cdf2cf0c201f39aab1a78) despite that code now looking correct.

### PR DESCRIPTION
**Pull request by nd2s**
would be good if someone could test fix for #34 just to be sure. looks good on my sys, though.

### CODE REVIEW

**Comment by nd2s** [comment]
Also exported `SyslogHandler` to be able to write type signatures (needed for writing log formatters).

**Comment by jgoerzen** [comment]
I reverted 71007bde29168c10ba26d8b9e3d7b4367009c0fc because it was not compiling on Debian jessie.  If you want to do this with a versioned bounds test with a preprocessor directive, I would apply that.

**Comment by nd2s** [comment]
Not compiling because the module is not found?

How about requiring mtl-2.2.1 in the cabal file instead? That version is from June 2014, if Debian can't keep their packages updated it's their problem. For development people use `stack` (or `cabal-install`) anyway and don't rely on the OS package management.

**Comment by jgoerzen** [comment]
Debian jessie ships with mtl 2.1.2.  I do not at all like the idea of breaking things just for the sake of breaking them.  As I said, a versioned bounds test would be fine with me.  This is a pretty common compatibility device all over.  I'm not going to intentionally inflict breakage on people for the sake of avoiding a warning.

**Pull request merged**
