### PR TITLE
Fix compilation for GHC 7.10

### PR DESCRIPTION
**Pull request by alanz**

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
I was going to write exactly this patch. I hope it gets merged soon. Thanks @alanz.

**Comment by hesselink** [comment]
Thanks for working on this! I don't think you should use the `__GLASGOW_HASKELL__` macro for this, since this is not a problem with new GHC versions, but with new `time` versions. You can use `MIN_VERSION_time(1,5,0)` instead, which is defined by cabal.

**Comment by Daniel-Diaz** [comment]
I agree with @hesselink.

**Comment by bgamari** [comment]
I've opened #29 which implements the cleaner `MIN_VERSION` approach.

**Comment by alanz** [comment]
Ok, I did update my original based on this feedback.

**Pull request merged**
